### ISSUE TITLE
File browser not working?

### ISSUE THREAD

**Issue by ndahn** [fabriciochamon/DearPyGui_Extend#3]
The file browser seems not to be working right now. The following code hangs indefinitely:

```python
import dearpygui.dearpygui as dpg
import dearpygui_extend as dpge

dpg.create_context()
dpg.create_viewport(title='Custom Title', width=600, height=600)

with dpg.window():
    dpge.add_file_browser(
        default_path='~/Downloads/images', 
        collapse_sequences=True, 
        sequence_padding='#',
    )

dpg.setup_dearpygui()
dpg.show_viewport()
dpg.start_dearpygui()
dpg.destroy_context()
```

Without the window it leads to an exception (even with `show_as_window=True`):

```
Exception: 
Error:     [1011]
Command:   add_*
Item:      41 
Label:     Choose file ...
Item Type: mvAppItemType::mvButton
Message:   Parent could not be deduced.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<my_path>/miniforge3/lib/python3.10/site-packages/dearpygui_extend/file_browser.py", line 823, in __init__
    try: dpg.add_button(label=fb_btn_label, callback=lambda x: dpg.configure_item(f'{tag_prefix}_window', show=True, pos=fb_win_pos))
  File "<my_path>/miniforge3/lib/python3.10/site-packages/dearpygui/dearpygui.py", line 3049, in add_button
    return internal_dpg.add_button(label=label, user_data=user_data, use_internal_label=use_internal_label, tag=tag, width=width, height=height, indent=indent, parent=parent, before=before, payload_type=payload_type, callback=callback, drag_callback=drag_callback, drop_callback=drop_callback, show=show, enabled=enabled, pos=pos, filter_key=filter_key, tracked=tracked, track_offset=track_offset, small=small, arrow=arrow, direction=direction, **kwargs)
SystemError: <built-in function add_button> returned a result with an exception set

During handling of the above exception, another exception occurred:

Exception: 
Error:     [1011]
Command:   add_*
Item:      42 
Label:     Choose file ...
Item Type: mvAppItemType::mvButton
Message:   Parent could not be deduced.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<my_path>/<pkg_path>/dpg_demo.py", line 7, in <module>
    dpge.add_file_browser(
  File "<my_path>/miniforge3/lib/python3.10/site-packages/dearpygui_extend/__init__.py", line 67, in add_file_browser
    return FileBrowser(**kwargs)
  File "<my_path>/miniforge3/lib/python3.10/site-packages/dearpygui_extend/file_browser.py", line 824, in __init__
    except: dpg.add_button(parent=parent, label=fb_btn_label, callback=lambda x: dpg.configure_item(f'{tag_prefix}_window', show=True, pos=fb_win_pos))
  File "<my_path>/miniforge3/lib/python3.10/site-packages/dearpygui/dearpygui.py", line 3049, in add_button
    return internal_dpg.add_button(label=label, user_data=user_data, use_internal_label=use_internal_label, tag=tag, width=width, height=height, indent=indent, parent=parent, before=before, payload_type=payload_type, callback=callback, drag_callback=drag_callback, drop_callback=drop_callback, show=show, enabled=enabled, pos=pos, filter_key=filter_key, tracked=tracked, track_offset=track_offset, small=small, arrow=arrow, direction=direction, **kwargs)
SystemError: <built-in function add_button> returned a result with an exception set
```

**Comment by fabriciochamon** [comment]
There is something weird going on with invalid directories. Please retry with "default_path" arg set to a valid folder and it should work.

I'll investigate the error, looks related to positioning of an error message popup window.

_edit: a temp fix would be to comment out line 157 on filebrowser.py_

**Comment by ndahn** [comment]
Ah, I see. With an actually existing path it works if embedded in a window. `show_as_window` still doesn't work even with an existing path, but that's fine for now. Thank you!

**Comment by fabriciochamon** [comment]
oh are you sure? I just tested with `show_as_window` and an existing folder and it worked fine here. Maybe there is a combination with other args that is making it not work in your case, if you could share a minimal example of your code I can take a look.

**Comment by ndahn** [comment]
```python
import dearpygui.dearpygui as dpg
import dearpygui_extend as dpge

dpg.create_context()
dpg.create_viewport(title='Custom Title', width=600, height=600)

dpge.add_file_browser(
    default_path='/',
    show_as_window=True,
)

dpg.setup_dearpygui()
dpg.show_viewport()
dpg.start_dearpygui()
dpg.destroy_context()
```

Pretty sure that path exists :) Error seems to be the same.

```
Exception: 
Error:     [1011]
Command:   add_*
Item:      41 
Label:     Choose file ...
Item Type: mvAppItemType::mvButton
Message:   Parent could not be deduced.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<my_path>miniforge3/lib/python3.10/site-packages/dearpygui_extend/file_browser.py", line 823, in __init__
    try: dpg.add_button(label=fb_btn_label, callback=lambda x: dpg.configure_item(f'{tag_prefix}_window', show=True, pos=fb_win_pos))
  File "<my_path>miniforge3/lib/python3.10/site-packages/dearpygui/dearpygui.py", line 3049, in add_button
    return internal_dpg.add_button(label=label, user_data=user_data, use_internal_label=use_internal_label, tag=tag, width=width, height=height, indent=indent, parent=parent, before=before, payload_type=payload_type, callback=callback, drag_callback=drag_callback, drop_callback=drop_callback, show=show, enabled=enabled, pos=pos, filter_key=filter_key, tracked=tracked, track_offset=track_offset, small=small, arrow=arrow, direction=direction, **kwargs)
SystemError: <built-in function add_button> returned a result with an exception set

During handling of the above exception, another exception occurred:

Exception: 
Error:     [1011]
Command:   add_*
Item:      42 
Label:     Choose file ...
Item Type: mvAppItemType::mvButton
Message:   Parent could not be deduced.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<my_path>/<my_project>/dpg_demo.py", line 7, in <module>
    dpge.add_file_browser(
  File "<my_path>miniforge3/lib/python3.10/site-packages/dearpygui_extend/__init__.py", line 67, in add_file_browser
    return FileBrowser(**kwargs)
  File "<my_path>miniforge3/lib/python3.10/site-packages/dearpygui_extend/file_browser.py", line 824, in __init__
    except: dpg.add_button(parent=parent, label=fb_btn_label, callback=lambda x: dpg.configure_item(f'{tag_prefix}_window', show=True, pos=fb_win_pos))
  File "<my_path>miniforge3/lib/python3.10/site-packages/dearpygui/dearpygui.py", line 3049, in add_button
    return internal_dpg.add_button(label=label, user_data=user_data, use_internal_label=use_internal_label, tag=tag, width=width, height=height, indent=indent, parent=parent, before=before, payload_type=payload_type, callback=callback, drag_callback=drag_callback, drop_callback=drop_callback, show=show, enabled=enabled, pos=pos, filter_key=filter_key, tracked=tracked, track_offset=track_offset, small=small, arrow=arrow, direction=direction, **kwargs)
SystemError: <built-in function add_button> returned a result with an exception set
```

**Comment by fabriciochamon** [comment]
oh I see.. you need to have a window to create the file browser button on, otherwise it can't find the parent. 
Add a **with dpg.window():** context manager before adding the file browser.

This should work:

```py
import dearpygui.dearpygui as dpg
import dearpygui_extend as dpge

dpg.create_context()
dpg.create_viewport(title='Custom Title', width=600, height=600)

with dpg.window():
	dpge.add_file_browser(
		default_path='/',
		show_as_window=True,
	)

dpg.setup_dearpygui()
dpg.show_viewport()
dpg.start_dearpygui()
dpg.destroy_context()
```

**Comment by ndahn** [comment]
Ah, I see... then maybe I got the meaning of "show_as_window" wrong.

**Comment by fabriciochamon** [comment]
Got it. So `show_as_window` is meant to be a shortcut for adding a simple "choose file" or "choose folder" button, that opens the filebrowser on its own window. But the main container(window) where this button is placed is still necessary. Otherwise when `show_as_window=False` the filebrowser is displayed inline, within the current dpg window. Hope that this clarifies the arg usage.
